### ISSUE TITLE
Documentation/Migration guide for PlutusV3

### ISSUE THREAD

**Issue by mesudip** [cardanoapi/hardfork-testing#6]
Prepare a migration guide similar to one we prepared for vasil hardfork.

**Comment by reeshavacharya** [comment]
> WIP  
# **Migrating Cardano-Marketplace from Plutus V2 to Plutus V3**

### **Cardano-Marketplace**
[Cardano Marketplace](https://github.com/dQuadrant/cardano-marketplace) is a straightforward DApp for an NFT marketplace utilizing Plutus smart contracts. It supports minting assets, selling them to the marketplace, purchasing them from the marketplace, and withdrawing them if you are the asset owner. Additionally, it can perform these tasks with reference scripts.

**Types**
- Simple Marketplace
    - Basic implementation for buying, selling, and withdrawing assets.
- Configurable Marketplace
    - Adds functionality for an additional fee payable to the market operator, with configurable fee amount and operator address.

The Cardano marketplace has been implemented using Plutus V1, V2, and V3. This article serves as a migration guide from Plutus V2 to Plutus V3.

### **Effects of Chang Hard Fork on DApps and Smart Contracts**
A significant change with the new Plutus dependency, as introduced by the [CIP-0069](https://developers.cardano.org/docs/governance/cardano-improvement-proposals/cip-0069/), affects the arguments given to all types of Plutus scripts:

>*"This CIP unifies the arguments given to all types of Plutus scripts currently available (spending, certifying, rewarding, minting) by removing the argument of a datum."*  

Developers must update their DApps if they wish to use the latest dependencies. Previously, all script purposes followed the form `Redeemer -> ScriptContext -> a`, except spending scripts which were `Datum -> Redeemer -> ScriptContext -> a`. With the changes from CIP-0069, both Redeemer and Datum can be decoded from ScriptContext, making the validator take only one argument: `ScriptContext -> a`. This same update applies to Cardano-Marketplace.

### **References**
- [**Plutus V2 ScriptContext**](https://github.com/IntersectMBO/plutus/blob/8c7a5f6aa80fff036537d4b130052ea9afe6c28b/plutus-ledger-api/src/PlutusLedgerApi/V2/Contexts.hs#L107)

- [**Plutus V3 ScriptContext**](https://github.com/IntersectMBO/plutus/blob/8c7a5f6aa80fff036537d4b130052ea9afe6c28b/plutus-ledger-api/src/PlutusLedgerApi/V3/Contexts.hs#L438)

- [**Plutus V3 ScriptInfo**](https://github.com/IntersectMBO/plutus/blob/8c7a5f6aa80fff036537d4b130052ea9afe6c28b/plutus-ledger-api/src/PlutusLedgerApi/V3/Contexts.hs#L360)

In V3, the scriptInfo can identify whether the script is for minting, spending, rewarding, certifying, voting, or proposing. Details about the datum can be obtained if the script is a spending script. This update changes the 3-parameter validator to a 1-parameter validator. The validator still takes an extra argument if the smart contract is to be parameterized. Also, the check function now returns a `BuiltinUnit` data type. Thus, a smart contract with V3 dependency looks like this:

```hs
validator :: BuiltinData -> BuiltinUnit
validator context = check $ validatorLogic (unsafeFromBuiltinData context) 
    where
        vaildatorLogic :: ScriptContext -> Bool
        vaildatorLogic = ... --decoding of the script-context for datum and redeemer information can be done here
```
For smart contracts using Plutus V2, the validator still takes 3 arguments, but the return type changes to BuiltinUnit. For example:

```hs
validator :: BuiltinData -> BuiltinData -> BuiltinData -> BuiltinUnit
validator datum redeemer context = 
    check $ 
        validatorLogic 
            (unsafeFromBuiltinData datum)
            (unsafeFromBuiltinData redeemer)
            (unsafeFromBuiltinData context)
    where 
        validatorLogic :: Datum -> Redeemer -> ScriptContext -> Bool 
        validatorLogic datum redeemer context = ...
```

### **What To Do**  

If developers want to use `PlutusLedgerApi.V2` dependencies, the only change needed is to the return type of the validator. Since the type signature for the check function has changed from `Bool -> ()` to `Bool -> BuiltinUnit`, the validator implementing this function must also return `BuiltinUnit`. This type is compatible with the `PlutusTx.compile` function.

This implementation has been tested and verified in the Cardano-Marketplace. Here is a sample of the validator using this upgrade:

```hs
{-# INLINABLE mkWrappedMarket #-}
mkWrappedMarket ::  BuiltinData -> BuiltinData -> BuiltinData -> BuiltinUnit
mkWrappedMarket  d r c = 
    check $ 
        mkMarket 
        (parseData d "Invalid data") 
        (parseData r "Invalid redeemer") 
        (parseData c "Invalid context")
  where
    parseData md s = case fromBuiltinData  md of 
      Just datum -> datum
      _      -> traceError s
```
to see the full implementation, visit [Cardano-MarketPlace-V2/SimpleMarketplace](https://github.com/dQuadrant/cardano-marketplace/blob/3f0e1290ea79f191511875221f41c9a90d852361/marketplace-plutus/Plutus/Contracts/V2/SimpleMarketplace.hs#L86)

For developers intending to use `PlutusLedgerApi.V3`, there needs to be additional changes in the smart contract code. A similar implementation using PlutusV3 for a simple marketplace can be found here: [Cardano-MarketPlace-V3/SimpleMarketplace](https://github.com/dQuadrant/cardano-marketplace/blob/3f0e1290ea79f191511875221f41c9a90d852361/marketplace-plutus/Plutus/Contracts/V3/SimpleMarketplace.hs#L122). In this implementation, the validator looks like this:

```hs
{-# INLINABLE mkWrappedMarket #-}
mkWrappedMarket ::  BuiltinData -> BuiltinUnit
mkWrappedMarket ctx = check $ mkMarket (parseData ctx "Invalid context")
```
It takes only one argument, `BuiltinData`, which is parsed into the `ScriptContext`.  

### **Decoding Datum and Redeemer** 
Decoding the datum and the redeemer now depends on the script's purpose. Mainly, DApps are developed with scripts whose purpose is to either mint, spend, certify, or reward. V3 offers additional purposes, including voting and proposing, related to governance actions introduced in the Chang hard fork. Let's look into decoding datum and redeemer.
  

**Decoding Datum**  
Datum is only needed when the script is of the spending type. Therefore, the datum will come from the `scriptInfo` in the `scriptContext`. Here is a simple example where we expect the script to be of the spending type and get the datum:  

```hs
ctx :: ScriptContext -- PlutusV3 script-context

scriptInfo :: ScriptInfo
scriptInfo = scriptContextScriptInfo ctx

datum :: Datum
datum = case scriptInfo of 
    SpendingScript outRef datum -> case datum of
          Just d ->  case fromBuiltinData (getDatum d) of
            Nothing -> traceError "Invalid datum format"
            Just v -> v
          Nothing -> traceError "Missing datum"
    _ -> traceError "Script Purpose Mismatch"
```

**Decoding Redeemer**  
For decoding the redeemer, we don't need to expect the script purpose to be of a particular type. It can be directly decoded from the scriptContext. For a scriptContext ctx, the redeemer can be extracted in the following way:
```hs
redeemer :: Redeemer
redeemer = case fromBuiltinData $ getRedeemer (scriptContextRedeemer ctx) of
    Nothing -> traceError "Invalid Redeemer"
    Just r -> r
```
Just like parsing datum to a correct data type, we can parse the redeemer to BuiltinData using getRedeemer first and then to the required data type using fromBuiltinData or unsafeFromBuiltinData.

For the simple cardano marketplace contract using PlutusV3, the validator logic function is available at [Cardano-Marketplace-V3/SimpleMarketplace](https://github.com/dQuadrant/cardano-marketplace/blob/3f0e1290ea79f191511875221f41c9a90d852361/marketplace-plutus/Plutus/Contracts/V3/SimpleMarketplace.hs#L80). This function takes ScriptContext only, with the decoding of datum and redeemer done inside the function.

## **Changes In Efficiency**
With more functionalities introduced in PlutusV3 for governance actions, the `ScriptContext` has additional fields. Because of this, the size of the script (in bytes) of smart contracts written using `PlutusLedgerApi.V3` has increased a considerable amount.   
A workaround to this problem is to write the validator lazily, not decoding the script-context entirely, but by only parsing the required fields contained within the script-context.   
The script-context initially will be of the form `BuiltinData`. We can then change this to a BuiltinList using the following function:

```hs
import qualified PlutusTx.Builtins.Internal as BI

constrArgs :: BuiltinData -> BI.BuiltinList BuiltinData
constrArgs bd = BI.snd (BI.unsafeDataAsConstr bd)
```

This allows us to extract only the necessary information from the script-context without needing to decode it fully, as the `unsafeFromBuiltinData` function does. But, this comes at the expense of a cleaner code. Indexing of a `BuiltinList` type is not supported in Plutus yet. So, we have to utilize the `BI.head` and `BI.tail` function repeatedly in order to get the element we want. For example, to get the datum and redeemer from script-context, the following approach can be followed:   
```hs
ctx :: BuiltinData 

context :: BI.BuiltinList BuiltinData
context = constrArgs ctx

redeemerFollowedByScriptInfo :: BI.BuiltinList BuiltinData
redeemerFollowedByScriptInfo = BI.tail context

redeemerBuiltinData :: BuiltinData
redeemerBuiltinData = BI.head redeemerFollowedByScriptInfo

scriptInfoData :: BuiltinData
scriptInfoData = BI.head (BI.tail redeemerFollowedByScriptInfo)

datumData :: BuiltinData
datumData = BI.head (constrArgs (BI.head (BI.tail (constrArgs scriptInfoData))))

redeemer :: Redeemer
redeemer = unsafeFromBuiltinData redeemerBuiltinData 

datum :: Datum
datum = unsafeFromBuiltinData (getDatum (unsafeFromBuiltinData datumData)) 

``` 
The lazy validator for the simple marketplace can be found here: [Cardano-Marketplace-V3/SimpleMarketplace-Lazy](https://github.com/dQuadrant/cardano-marketplace/blob/3f0e1290ea79f191511875221f41c9a90d852361/marketplace-plutus/Plutus/Contracts/V3/SimpleMarketplace.hs#L126)

This method can be taken to the next with super lazy evaluation, where we decode the `txInfo` to obtain the required inputs, outputs, signatures, etc., for the validation logic, while ignoring the unused fields. For instance, the following method can be used to get the inputs, reference inputs, outputs and signature of a transaction from a script-context. 

```hs

```

> currently blocked due to server and kuber issue

**Comment by reeshavacharya** [comment]
> Non Technical report

# **Implementing Cardano Marketplace in Plutus V3**

**Cardano-Marketplace**  
The [Cardano Marketplace](https://github.com/dQuadrant/cardano-marketplace) is a decentralized application (DApp) for buying and selling NFTs, built with Plutus smart contracts. It comes in two flavors:
- **Simple Marketplace**: Basic functionality for buying, selling, and withdrawing assets.
- **Configurable Marketplace**: Adds a feature to charge a fee, payable to the market operator, with configurable fee amounts and operator addresses.  

The DApp has versions using Plutus V2 and V3. We will analyze the changes in efficiency, specifically execution units, fees, and script sizes. The smart contracts for the marketplace are written using the following implementations:
- Plutus V2
    - Uses `PlutusLedgerApi.V2` and its `ScriptContext`
- Plutus V3 
    - Uses `PlutusLedgerApi.V3` and its `ScriptContext`
- Lazy (V3) 
    - Uses `PlutusLedgerApi.V3` but avoids decoding the entire `ScriptContext`. It decodes the context only one step to obtain the `TxInfo` field, the redeemer, and the datum from `ScriptInfo`, all of which are included in the `ScriptContext`. 
- Super Lazy (V2 and V3)
    - Uses the LedgerApi version V2 and V3 but does not pass the entire `ScriptContext`. Instead, it extracts the script context to get the `TxInfo` field and further extracts it to obtain the necessary transaction objects for validation, such as outputs, inputs, reference inputs, and signatures. This way, the contract does not need to decode the entire script context, only the necessary fields for validation are passed.  

### **Efficiency Report**
The detailed report on script implementations for the cardano marketplace reveals significant insights into the efficiency of various versions of Plutus scripts. The marketplace was tested using the afforementioned implementations. Each implementation was evaluated based on script size (in Bytes), execution units (Ex-Units) for both memory and CPU, transaction fees, and transaction bytes.

| Market Type          | Implemented With | ScriptBytes |
| -------------------- | ---------------- | ----------- |
| **Simple Market**    |                  |             |
|                      | V2               | 4594        |
|                      | V2 Super Lazy    | 2848        |
|                      | V3               | 8118        |
|                      | V3 Lazy          | 7125        |
|                      | V3 Super Lazy    | 2573        |
| **Configurable Market** |               |             |
|                      | V2               | 3615        |
|                      | V2 Super Lazy    | 2875        |
|                      | V3               | 7883        |
|                      | V3 Lazy          | 7263        |
|                      | V3 Super Lazy    | 2586        |

> Click [here](https://github.com/dQuadrant/cardano-marketplace/blob/dev/reports/test-sanchonet-cardano-api-9.0.0/2024-07-23_10-52-57-transaction-report.md) to view the full report

<br> 

### **Analysis**
<br>

**Script Size**  
It's evident that the V3 implementations tend to have larger script sizes compared to the V2 implementations. This is due to the additional fields included in the `TxInfo` field of V3 to support governance actions. However, the Super Lazy versions of both V2 and V3 demonstrate remarkable efficiency in script size. This reduction is achieved through optimization techniques in the Super Lazy implementations, where only the necessary parts of the ScriptContext are decoded. However, the Super Lazy implementation of V3 is still more efficient in terms of size compared to the same implementation in V2.

**Fees**  
For transactions using V2 and V3 scripts without the lazy implementation, V3 transactions generally incur higher fees compared to V2. This is due to the larger script size of V3, which results in a bigger transaction size and thus higher fees. However, with the super lazy implementation, V3 has a slight advantage over V2, as it results in a lower fee.

**Execution Units**  
V3 scripts are more efficient than V2 scripts in terms of execution units, including both memory and CPU, even without the lazy implementation. Despite the additional fields in the `TxInfo` field that increase the script size, V3 transactions require less memory and CPU compared to V2. This efficiency is further enhanced with the Super Lazy implementation of V3, where the difference in execution unit efficiency compared to V2 becomes even more pronounced.

Overall, while V3 scripts inherently involve larger sizes and potentially higher fees, their efficiency in terms of execution units—especially with the Super Lazy implementation—demonstrates a significant advantage over V2.

**Comment by mesudip** [comment]
TODO make a docs file from these content

**Comment by reeshavacharya** [comment]
Article: 
- https://docs.google.com/document/d/19EQ7ZAewI9nemFlNQa1VxL_CBpgSdZYv3_CNGbGWUew/edit?usp=sharing

Migration Guide
- https://docs.google.com/document/d/1dTVfZZG5XBsgrGMoV6S9b4c-U3zxA7OD8-9w-Myr6js/edit?usp=sharing

**Comment by spannercode** [comment]
This is the final document shared with Intersect to share with the community.
https://github.com/cardanoapi/hardfork-testing/blob/main/migration.md
